#!/usr/bin/python3

import sys
import time

def factorize(n):
	factors = []

	for i in range(2, int(n**0.5) + 1):
		while n % i == 0:
		factors.append(i)
		n //= i

		if n > 1:
		factors.append(n)
	return (factors)

defmain():
	if len(sys.argv) !=2:
	print("Usage: factors <file>")
	return

	input_file = sys.argv[1]

	try:
	with open(in_file, 'r') as file:
	numbers = file.read().splitlines()

	for num_str in numbers:
	num = int(num_str)
	factors_list = factorize(num)
	factors_str = '*'.join(map(str, factors_list))
	print(f"{num}={factors_str}")

	except FileNotFoundError:
	print("File not Found.")
	except Exception as e:
	print (f"An error occured: {e}")

	if __name__ == "__main__":
	main()

